<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

	<Import Project="$(SolutionDir)ProjectReferences_$(SolutionName).txt" Condition="Exists('$(SolutionDir)ProjectReferences_$(SolutionName).txt')" />
	<Choose>
		<When Condition="Exists('$(HaleyRestProj)')">
			<ItemGroup>
				<ProjectReference Include="$(HaleyRestProj)">
					<Name>HaleyRest</Name>
				</ProjectReference>
			</ItemGroup>
		</When>
		<Otherwise>
			<ItemGroup>
				<PackageReference Include="Haley.Rest" Version="2.0.6.3" />
			</ItemGroup>
		</Otherwise>
	</Choose>

</Project>
