<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\HaleyProject\HaleyVersion.Props" />
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>HaleyProject.snk</AssemblyOriginatorKeyFile>
    <AssemblyName>Haley.Rest</AssemblyName>
    <RootNamespace>Haley.Rest</RootNamespace>
    <Description>A Simple HttpClient Wrapper to handle Http Requests.</Description>
    <PackageIcon>Haley.png</PackageIcon>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Product>Haley Helpers</Product>
    <PackageId>Haley.Rest</PackageId>
    <Version>$(HaleyRestVersion)</Version>
    <PackageProjectUrl>$(ProjectBaseUrl)Rest</PackageProjectUrl>
    <RepositoryUrl>$(ProjectBaseUrl)Rest</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
	  <IncludeSymbols>true</IncludeSymbols>
	  <SymbolPackageFormat>snupkg</SymbolPackageFormat>
	  <PackageReleaseNotes>Added httpclienthandler to constructor with Sethandler</PackageReleaseNotes>
	  <Configurations>Debug;Release;Debug_Net6</Configurations>
  </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>portable</DebugType>
		<DebugSymbols>true</DebugSymbols>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
		<DebugType>full</DebugType>
		<DebugSymbols>true</DebugSymbols>
		<WarningLevel>2</WarningLevel>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
	</PropertyGroup>
  
<ItemGroup>
  <Compile Remove="Models\Base\MicroClient-OLD.cs" />
  <Compile Remove="Utils\RestWrappers.cs" />
</ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Haley.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Events\" />
  </ItemGroup>

<Import Project="$(SolutionDir)ProjectReferences_$(SolutionName).txt" Condition="Exists('$(SolutionDir)ProjectReferences_$(SolutionName).txt')" />
	<!--<Choose>
    <When Condition="Exists($(HaleyExtensions))">
      <ItemGroup>
        <ProjectReference Include="$(HaleyExtensions)\HaleyExtensions.csproj">
          <Name>HaleyExtensions</Name>
        </ProjectReference>
      </ItemGroup>
    </When>
    <Otherwise />
</Choose>-->
  <Choose>
    <When Condition="Exists($(HaleyHelpers))">
      <ItemGroup>
        <ProjectReference Include="$(HaleyHelpers)\HaleyHelpers.csproj">
          <Name>HaleyHelpers</Name>
        </ProjectReference>
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <PackageReference Include="Haley.Helpers" Version="$(HaleyHelpersVersion)" />
      </ItemGroup>
    </Otherwise>
  </Choose>
</Project>
